from dataclasses import dataclass
from typing import Any, Optional

@dataclass
class AgentEvent:
    """
    Structured Event generated by Agent Engine
    
    Used to distinguish different data types in streaming output (Token, Message, Tool Call, Finish Signal, etc.).
    """
    type: str  # "token", "tool_call", "tool_result", "message", "finish", "error"
    data: Any
    
    # Helper method: check if finish event
    @property
    def is_finish(self):
        return self.type == "finish"
